# Generated by Django 6.0.2 on 2026-02-14 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('search_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_logs',
                'ordering': ['-search_time'],
                'indexes': [models.Index(fields=['source', 'destination'], name='search_logs_source_2c02f1_idx'), models.Index(fields=['search_time'], name='search_logs_search__82a4ea_idx')],
            },
        ),
    ]
